### ISSUE TITLE
Chapter 5 Question 6

### ISSUE THREAD

**Issue by donnice** [ilmoi/MMLBook#6]
First of all, thanks for your solution sheet!

For 5.6, I believe d(**g**)/d(**X**) =A<sup>T</sup>B<sup>T</sup>. Because A is DxE, and B is FxD. A<sup>T</sup>B<sup>T</sup> is valid, while B<sup>T</sup>A<sup>T</sup> is not.

**Comment by AlbertoGuastalla** [comment]
Yes, therefore BA.
